version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: python main.py

  db:
    image: postgres:13
    container_name: db
    # restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kokos
    # ports:
    #   - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  assets_contain:
    build: ./assets_contain
    container_name: assets_contain
    # restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - db
    command: python assets_delivery.py
  
  admin_panel:
    build: ./admin_panel
    container_name: assets_contain
    # restart: unless-stopped
    ports:
      - "5002:5002"
    depends_on:
      - db
    command: python admin_app.py
