version: '3.8'

services:
  web:
    build: ./web
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase

  db:
    image: postgres:16.4
    # restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pgdata:
